const tintColorLight = '#FF3F6C';
const tintColorDark = '#FF3F6C';

export const Colors = {
  light: {
    text: '#282C3F',
    background: '#FFFFFF',
    tint: tintColorLight,
    icon: '#696B79',
    tabIconDefault: '#94969F',
    tabIconSelected: tintColorLight,
    primary: '#FF3F6C',
    secondary: '#14CDA8',
    accent: '#FF905A',
    surface: '#F8F8F8',
    cardBackground: '#FFFFFF',
    border: '#E9E9ED',
    muted: '#94969F',
    success: '#03DAC6',
    warning: '#FFAB00',
    error: '#FF3F6C',
  },
  dark: {
    text: '#FFFFFF',
    background: '#0A0A0A',
    tint: tintColorDark,
    icon: '#94969F',
    tabIconDefault: '#696B79',
    tabIconSelected: tintColorDark,
    primary: '#FF3F6C',
    secondary: '#14CDA8',
    accent: '#FF905A',
    surface: '#1A1A1A',
    cardBackground: '#2A2A2A',
    border: '#3A3A3A',
    muted: '#696B79',
    success: '#03DAC6',
    warning: '#FFAB00',
    error: '#FF3F6C',
  },
};
