version: '3.8'

services:
  body-measure-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./weights:/app/weights
      - ./test:/app/test
      - .:/app
    environment:
      - PYTHONPATH=/app
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    restart: unless-stopped
